### ISSUE TITLE
Avoid sending form-data FROM user's e-mail address

### ISSUE THREAD

**Issue by jonaslepsoy** [enonic/app-formbuilder#10]
https://github.com/enonic/app-formbuilder/blob/54126253d273f454b022dd88d1b06a5557507b4e/src/main/resources/lib/form-builder/form-response.js#L349

Using the client's email address in the From header is not good practice. Another word for this is email spoofing (see https://en.wikipedia.org/wiki/Email_spoofing). A properly configured email server should block these emails, as they do not conform to the SPF or DMARC policy of the sender's domain. We have seen real-world examples of this.

Using the Reply-To header is the correct way to handle cases were mail is sent on behalf someone else. The From header should contain the real sender. The Reply-To address should be an address for the requesting party.

Please move `userEmailAddr` to the Reply-To header, and use only `systemEmailAddr` as the From header.

**Comment by hjelmevold** [comment]
Pull requests merged into master branch.
