### ISSUE TITLE
Blank receipt page on "Minimal" storage of user-submitted data

### ISSUE THREAD

**Issue by jonaslepsoy** [enonic/app-formbuilder#3]
To reproduce:

1. Set up an empty Enonic XP instance, v6.15.5
2. Install Corporate Theme app from Enonic Market
3. Install Form Builder app from Enonic Market
4. Add Form Builder app to Corporate Theme site
5. Configure Form Builder app to use "Minimal" storage, and add a receipt text
6. Set up a form page
7. Enter data in form and submit

The receipt page is blank.

Changing the Form Builder app to use "Regular" or "Full" storage produces the expected receipt.

**Comment by hjelmevold** [comment]
Fixed in v1.1.0
