### ISSUE TITLE
Only users with write permissions for the form should be able to see answers

### ISSUE THREAD

**Issue by sigdestad** [enonic/app-formbuilder#9]
Add this check to the widget panel

**Comment by hjelmevold** [comment]
Done. If the user has a role that has write permissions on the form content, the widget is shown.

**Comment by sigdestad** [comment]
Does it have to be a role? What if it is a group or transitive membership or directly on the user?

**Comment by hjelmevold** [comment]
Ah, all the perspectives that I've never had to consider before, when I was used to the content library resolving everything for me automagically ;-)

**Comment by sigdestad** [comment]
From the context, you should be able to get all principals (even the transitive ones) and then see if any of these have write permission on the item.

**Comment by hjelmevold** [comment]
Write permission checks in the widget panel have now been implemented and will be part of the 2.1 release (rudimentary support for file inputs and downloading of files from reports)
